# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61264c28cc67b23dcfcdfb0267dd25152965e2d66c6fb0d6ffe498ec00d9036cad8ce18d26ecff3e1ef940996530d6f51a9388f4cfff54988d7968968429e766

test:
  secret_key_base: 9189cfd12908cd40bbb8854ed4a45957d9df6aee5f63ff42a03a3d3dfae4f57c54ec56ab01b4c2e0361836b85b3dcf63970ca7904eb380f13c72859cfb009141

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
